#doc.server: #升级到spring boot后就不用这么麻烦了，直接使用@ConfigurationProperties(prefix = "doc.server")
# 以下账户配置为客户端上传下载需要做的一个权限认证操作，需要在客户端进行配置
accounts:
  - userName: fortune
    password: fortune
    # 在idea中执行的话，需要配置target目录下的打包文件
    rootPath: C:\03_code\idea_workspace\fortune-commons\commons-doc-server-netty\target\commons-doc-server-netty\ #上传文件的根目录,实际工作环境按照实际情况更改即可
    level: 1
    thumbHeight: 100
    thumbWidth: 100
  - userName: fortune0
    password: fortune0
    # 也可以单独把打包后的war包拷贝到tomcat webapp目录下直接运行也可以
    rootPath: C:\05_webserver\apache-tomcat-8.5.42\webapps\doc-server #上传文件的根目录,实际工作环境按照实际情况更改即可
    level: 1
    thumbHeight: 100
    thumbWidth: 100
port: 9999 #端口号
fileBaseDirectory: C:\06_temp\up\tmp #临时文件的目录