#緩存服務公共配置
data:
  cache:
    common:
      #缓存策略，可选值：local/mongodb/redis/memcached
      cacheStrategy: "mongodb"
      mappingLocalFlag: true
      #映射到本地缓存的过期时间（单位：S）
      expiredTime: 10
      cacheKeyPrefix: "fortune_"
      loadFlag: true
    server:
      host: 127.0.0.1
      port: 28028
      account: fortune
      password: fortune

#MongoDB配置
mongodb:
  database: "fortune"
  collectionName: "global_data"

#MemCached配置
memcache:
  initConn: 50
  minConn: 50
  maxConn: 500
  #Memcached缓存过期时间(s)
  expiredTime: 30

#Redis配置



